### ISSUE TITLE
Does this lib work in actual iOS emulator?

### ISSUE THREAD

**Issue by jessilang** [shannah/CN1Sockets#10]
Hello,

I am not sure if this is suppose to be an issue, but here goes.

I tried to run a test app in an actual iPhone 6 emulator and it gave the following error: 

java.io.IOException
    at ca_weblite_codename1_net_Socket_SocketOutputStream.write:288
    at java_io_DataOutputStream.write:90
    at java_io_OutputStream.write:53
    at com_socktest_echo_EchoSocketApp.sendText:141
    at com_socktest_echo_EchoSocketApp.lambda$null$0:74
    at com_socktest_echo_EchoSocketApp__Lambda_6.run:276
    at com_codename1_ui_Display.processSerialCalls:1114
    at com_codename1_ui_Display.edtLoopImpl:1058
    at com_codename1_ui_Display.mainEDTLoop:946
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176
    at java_lang_Thread.runImpl:153 the 

However, when I tried it in the CN1 emulator, it works fine.

Also, I tried your example in the Readme.md for connecting to "example.com", in the CN1 emulator and it gave a timeout exception:

java.io.IOException: connect timed out
	at ca.weblite.codename1.net.Socket.connect(Socket.java:109)
	at ca.weblite.codename1.net.Socket.<init>(Socket.java:73)
	at ca.weblite.codename1.net.Socket.<init>(Socket.java:49)
	at com.testsoc.socket.CN1Socket.runSocketTests(CN1Socket.java:81)
	at com.testsoc.socket.CN1Socket$1$1.run(CN1Socket.java:54)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1116)
	at com.codename1.ui.Display.edtLoopImpl(Display.java:1060)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:948)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

Am I using the library incorrectly or is this library unstable?

Many thanks for your response.

**Comment by shannah** [comment]
You're probably hitting issues with iOS transport settings.  

See 

https://www.codenameone.com/blog/ios-http-urls.html

and

https://stackoverflow.com/a/33210575

**Comment by jessilang** [comment]
I tried to disable the <key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key<true/></dict>, but it still gave the same errors. 

Also the second example based on what you wrote in the Readme.md, when executed in CN1 emulator (not in iOS) it gave timeout errors.

**Comment by shannah** [comment]
What exactly do you have for the ios.plistInject build hint?

**Comment by jessilang** [comment]
exactly the same as written in the blog.

**Comment by jessilang** [comment]
You should also try the example code you gave in the Readme in a CN1 emulator and it will give timeout errors.

**Comment by shannah** [comment]
I just copied and pasted the sample in the README into a project, with the correct transport settings, and it worked fine.

![image](https://user-images.githubusercontent.com/2677562/35935213-ab20cf2a-0bf4-11e8-8d6a-2dfedd91652d.png)

That is an iPhone 6s simulator (11.2)

**Comment by shannah** [comment]
Are you using the cn1lib from Codename One settings? or did you build it yourself?

**Comment by jessilang** [comment]
Interesting. For the timeout exception, I downloaded this cn1lib thru the Codename One Settings tool into a new project. Then I copied the example from the Readme, in this project. When I run it using the default CN1 emulator, it throws a timeout exception like I described above. I have updated to the latest CN1 project library and using jdk 8_u162. I will use this example on actual iOS emulator and see what happens because previously I used my own example.

**Comment by jessilang** [comment]
I downloaded the source and run it in xcode, this is the exception I got: 

2018-02-08 19:28:01.890 CN1Socket[4007:58419] Connecting to plain socket example.com:80
2018-02-08 19:28:02.070 CN1Socket[4007:58419] [EDT] 0:0:8,368 - We have an error
2018-02-08 19:28:02.072 CN1Socket[4007:58419] [EDT] 0:0:8,370 - Exception: java.io.IOException - Failed to connect to server socket because connection timed out: null
2018-02-08 19:28:02.072 CN1Socket[4007:58419] java.io.IOException
    at ca_weblite_codename1_net_Socket.connect:109
    at ca_weblite_codename1_net_Socket.__INIT__:73
    at ca_weblite_codename1_net_Socket.__INIT__:49
    at com_renerfa_socket_CN1Socket.runSocketTests:81
    at com_renerfa_socket_CN1Socket_1_1.run:54
    at com_codename1_ui_Display.processSerialCalls:1129
    at com_codename1_ui_Display.edtLoopImpl:1073
    at com_codename1_ui_Display.mainEDTLoop:961
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176
    at java_lang_Thread.runImpl:153
2018-02-08 19:28:02.073 CN1Socket[4007:58419] 

Don't think its any firewall issues caus I can access the site.  I am not sure where I went wrong because I watched your videos and read the ReadMe and used all built hints that are required.

**Comment by shannah** [comment]
I was using the version from Codename One settings.  That's one possible difference.  Though should be the same.

Please post your info.plist file.  That might offer a clue.

**Comment by jessilang** [comment]
[CN1Socket-Info.zip](https://github.com/shannah/CN1Sockets/files/1708248/CN1Socket-Info.zip)

**Comment by jessilang** [comment]
![build_hints](https://user-images.githubusercontent.com/13584815/35990233-15b2dd20-0d0c-11e8-9888-352f922e7bea.jpg)

**Comment by shannah** [comment]
Looks like the default timeout is set to 30ms -- should have been 30 seconds.  If you set the timeout explicitly to something more reasonable, it should work.

**Comment by jessilang** [comment]
where do I set default timeout?

**Comment by shannah** [comment]
It's a parameter in the Socket constructor.
Or download the latest here https://github.com/shannah/CN1Sockets/blob/master/dist/CN1Sockets.cn1lib?raw=true

**Comment by jessilang** [comment]
Yep its working. The library I got from Codename One settings did not have timeout parameter? I didn't notice. I think I will just grab the latest dist from now on. Also, do you support security transport like SSL/TLS thru your socket lib?

**Comment by shannah** [comment]
No support for SSLSocket at this time.

BTW.  Unless you absolutely need "real" sockets, I recommend using websockets, as they are simpler, and more portable.

**Comment by jessilang** [comment]
Thanks for the tip. However, I have to use "real" sockets. Any chance it will support SSL considering Apple's strigent secure transport requirements or don't they care about raw sockets connections, only HTTPS?

Anyway, it seems one cannot wrap the socket streams in a DataInputStream or a DataOutputStream for example. By doing so would cause an exception to be thrown (see my first comment).

**Comment by shannah** [comment]
Open a new issue for the DataInputStream issue.  Include a self-contained test case
