### ISSUE TITLE
Socket output stream wrapped inside DataOutputStream causes IOException during write().

### ISSUE THREAD

**Issue by jessilang** [shannah/CN1Sockets#11]
Consider the following: 

Socket soc = ....
DataOutputStream out = new DataOutputStream(soc.getOutputStream());
out.write(data);  <-- IOException

This will cause an exception to be thrown if socket stream is wrapped inside DataOutputStream in this example:

2018-02-09 13:04:13.561 EchoSocketApp[6692:29280] java.io.IOException
    at ca_weblite_codename1_net_Socket_SocketOutputStream.write:288
    at java_io_DataOutputStream.write:90
    at java_io_OutputStream.write:53
    ...

It might affect other standard Java stream handling classes when wrapped inside them, although its not tested comprehensively. 

However, when socket is used standalone, it is fine:

Socket soc = ....
OutputStream out = soc.getOutputStream();
out.write(data);   <-- No problems

**Comment by shannah** [comment]
Please post a self-contained test case that I can paste into a project and try out myself.  Or at least something that can be replicated with a reasonable amount of setup.

For something like this, if you can use some sort of java socket echo server that can easily be installed by cloning a github repo and running an ant or maven target, then provide the CN1 client code to reproduce the problem, that would be ideal.

**Comment by jessilang** [comment]
You can use your Readme example that connects to "example.com" and wrap the output socket stream inside a DataOutputStream. It will throw the IOException like I described.

Note that this exception only occurs when run on iOS. Haven't tested on Android, but it works in CN1 Emulator in Java.

**Comment by shannah** [comment]
Then use that as your test case that you post here.

**Comment by shannah** [comment]
Just *embed* the source in the issue.  I have an endless queue or issues.  Issues that can easily be replicated (i.e. I can paste something into a project to see it happen) will usually be dealt with sooner.

**Comment by jessilang** [comment]
`import ca.weblite.codename1.net.Socket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.Util;
import com.codename1.ui.Button;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import java.io.DataOutputStream;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class CN1Socket {

    private Form current;
    private Resources theme;
    private Label lbl;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        lbl = new Label("Result here");
        Form hi = new Form("Socket Tester");
        Button btn = new Button("Run Test");
        btn.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent evt) {
                Display.getInstance().callSerially(new Runnable(){

                    public void run() {
                        runSocketTests();
                    }
                    
                });
            }
            
        });
        
        hi.addComponent(btn);
        hi.addComponent(lbl);
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

    public void runSocketTests() {
        try {
            if (Socket.isSocketSupported()) {
                Socket sock = new Socket("example.com", 80, 30000);
                DataOutputStream dOut = new DataOutputStream(sock.getOutputStream());
                dOut.write("GET / HTTP/1.0\r\nHost: example.com\r\n\r\n".getBytes());

                String result = Util.readToString(sock.getInputStream());
                // NOTE:  Util.readToString() closes the input stream automatically.
                // Don't use it if you need to keep the socket open.  Use
                // another mechanism to read the stream.
                lbl.setText(result);
                //sock.close();
                Log.p(result);
            } else {
                lbl.setText("Sockets not supported");
                Log.p("Sockets not supported");
            }
        } catch (Exception ex) {
            Log.p("We have an error");
            Log.e(ex);

        }
    }
}`
