### ISSUE TITLE
Build Hints ios.add_libs=CFNetwork.framework

### ISSUE THREAD

**Issue by PiotrZub** [shannah/CN1Sockets#5]
To compile new version for iOS we need to add build hints:
ios.add_libs=CFNetwork.framework

Be careful it is case sensitive so Framework is not OK.
To change option you must put enter and than OK. If you put only OK new hints are saved.

**Comment by shannah** [comment]
That's strange.  I didn't need to do this.  Are you on old or new VM?

**Comment by shannah** [comment]
Sorry... I see that the app I was working on already had that build hint.
